# -*- coding: utf-8 -*-
"""2343551 OSS 과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leH2J20Hv-NEs3sMmiztBlez_txad2k0
"""

# 당뇨병 환자 데이터세트 가져오기
from sklearn import datasets
from sklearn.model_selection import train_test_split
diabetes = datasets.load_diabetes()

X = diabetes.data
y = diabetes.target

#train 데이터와 test 데이터를 80:20으로 분할.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

print(X_train.shape)
print(X_test.shape)
print(diabetes.feature_names) #데이터 셋의 변수 이름

