# -*- coding: utf-8 -*-
"""2343551 OSS 과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leH2J20Hv-NEs3sMmiztBlez_txad2k0
"""

# 당뇨병 환자 데이터세트 가져오기
from sklearn import datasets
from sklearn.model_selection import train_test_split
diabetes = datasets.load_diabetes()

X = diabetes.data
y = diabetes.target

#train 데이터와 test 데이터를 80:20으로 분할.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


#선형회귀 모델 작성
import numpy as np
from sklearn.linear_model import LinearRegression
class LinearRegression():
  def __init__(self,learning_rate = 0.01, epochs = 1000):
    self.learning_rate = learning_rate
    self.w = None #모델의 가중치 초기 값
    self.b = None #모델의 바이어스 초기 값
    self.epochs = epochs
    self.loss_list = []

  def predict(self,X):
      return np.dot(X, self.w) + self.b
      
  def fit(self, X_train, y_train):
    N,M = X_train.shape
    self.w = np.zeros(M) # 모델 가중치 초기화
    self.b = 0.0 #바이어스 초기화
    
    for epoch in range(self.epochs): #경사 하강법
      y_pred = self.predict(X_train)
      error = y_pred - y_train
      dw = (2 / N) * np.dot(X_train.T, error)
      db = (2 / N) * np.sum(error)
      self.w -= self.learning_rate * dw
      self.b -= self.learning_rate * db
      loss = np.mean(error**2)
      self.loss_list.append(loss)

model = LinearRegression(learning_rate= 0.1, epochs= 5000)
model.fit(X_train, y_train) #모델 학습

y_pred = model.predict(X_test) #예측

from sklearn.metrics import mean_squared_error, r2_score

MSE = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE : {MSE:.2f}")
print(f"결정 계수: {r2:.2f}")
print(f"Loss : ", model.loss_list[-1])